# Generated by Django 5.2.10 on 2026-02-11 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRE_ENROLLED', 'Pré-inscrit'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En cours de revue'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('FINALIZED', 'Finalisé')], default='PRE_ENROLLED', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('course', 'candidate')},
            },
        ),
    ]
