# Generated by Django 5.2.11 on 2026-02-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV ou Dossier de candidature', null=True, upload_to='enrollments/cvs/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PRE_ENROLLED', 'Pré-inscrit'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En cours de revue'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('FINALIZED', 'Finalisé')], default='SUBMITTED', max_length=20),
        ),
    ]
