# Generated by Django 5.2.11 on 2026-02-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_cv_file_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='diplome_file',
            field=models.FileField(blank=True, help_text='Copie du dernier diplôme obtenu', null=True, upload_to='enrollments/diplomes/'),
        ),
    ]
