# Generated by Django 5.2.11 on 2026-02-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_diplome_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
