# Generated by Django 5.2.11 on 2026-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_establishment_address_establishment_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', help_text='Ex: 2025-2026', max_length=20)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configuration Système',
            },
        ),
    ]
