AWSTemplateFormatVersion: '2010-09-09'
Description: 'PFE Milestone 4 : Cluster ECS Fargate et Service Applicatif'

Parameters:
  ContainerPort:
    Type: Number
    Default: 8000
    Description: Port d'écoute de ton application (modifier si ton app tourne sur 5000 ou 8080)


Resources:
  PfeCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: pfe-cluster

  EcsSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Autorise le trafic entrant uniquement depuis ALB
        VpcId: !ImportValue PfeVpcId
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: !Ref ContainerPort
            ToPort: !Ref ContainerPort
            SourceSecurityGroupId: !ImportValue PfeAlbSecurityGroupId

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !ImportValue pfe-db-secret-arn

  PfeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/pfe-app
      RetentionInDays: 7

  PfeTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pfe-app-task
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: cfc-backend-container
          Image: 311141564701.dkr.ecr.us-east-1.amazonaws.com/pfe-app-repo:latest
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          Environment:
            - Name: DB_HOST
              Value: !ImportValue pfe-rds-endpoint
            - Name: DB_PORT
              Value: !ImportValue pfe-rds-port
            - Name: DB_NAME
              Value: cfcdb
            - Name: DB_USER
              Value: cfcadmin
          Secrets:
            - Name: DB_PASSWORD
              ValueFrom: !Join [ '', [ !ImportValue pfe-db-secret-arn, ':password::' ] ]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref PfeLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  PfeService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref PfeCluster
      ServiceName: pfe-app-service
      TaskDefinition: !Ref PfeTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref EcsSecurityGroup
          Subnets:
            - !ImportValue PfePublicSubnet1Id
            - !ImportValue PfePublicSubnet2Id
      LoadBalancers:
        - ContainerName: cfc-backend-container
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !ImportValue PfeTargetGroupArn